--- 
- :xtype: ""
  :home: ""
  :url: ""
  :text: OPS
  :cls: folder
  :leaf: false
  :application_type: application_module
  :id: 17
- :xtype: ""
  :home: ""
  :url: ""
  :text: Searching
  :cls: folder
  :leaf: false
  :application_type: application_module
  :id: 4